name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      COHERE_API_KEY: ''
      ZOTERO_LIBRARY_ID: ''
      ZOTERO_LIBRARY_TYPE: 'user'
      ZOTERO_API_KEY: ''
      CHROMA_DB_PATH: './chroma_db'
      MODELS_PATH: './models'
      DOCS_PATH: './docs'
      RECOMMENDATIONS_PATH: './recommendations'
    steps: [uses: fastai/workflows/quarto-ghp@master]
