name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup nbdev-ci with Python 10
        uses: fastai/workflows/nbdev-ci@master
        with:
          version: '3.10' # python version to use for this step    